apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: revshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: revshop-mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: revshop_007
            - name: MYSQL_ROOT_PASSWORD
              value: Dinesh
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql  # Mounting PVC to MySQL data directory
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
