apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: revshop
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
